Cleanup
OpenCyphal-Garage/libudpard pull request #15
Opened 2023-03-29 23:03 UTC by SchoberMJ

Changes to enable workflows and some clean up per latest changes from libcyphal development

2023-04-27 21:30 UTC, thirtytwobits requested changes

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.c
> -        if (local_node_id <= UDPARD_NODE_ID_MAX)
why did we remove this check?

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.c
> +    if (frame->source_node_id != UDPARD_NODE_ID_UNSET)
why did we remove the check on UDPARD_NODE_ID_MAX?

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.c
> +static const uint16_t UDPARD_SUBJECT_ID_MASK = 32767U;  /// 0x7FFF
why not express this as hex?

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.c
> +// static const uint32_t UDPARD_SUBNET_OFFSET = 17U;
remove commented out code or un-comment.

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.c
> +        header->data_specifier =  (uint16_t)(port_id & UDPARD_SUBJECT_ID_MASK) & UPDARD_DATA_SPECIFIER_MESSAGE;  // SNM (0) + Subject ID
1. UPDARD_DATA_SPECIFIER_MESSAGE should be renamed to UPDARD_DATA_SPECIFIER_MESSAGE_MASK
2. When transforming a type with one mask to a type with another mask you typically have a shift value as well. 
3. Omit cast. Should be redundant.
4. there's no indication of what 15 is.

Taken together:
```
// both port_id and the data_specifier start at bit-0. No shift of the port_id value is necessary.
header->data_specifier = (0 << UDPARD_DATA_SPECIFIER_SNM_SHIFT) | (UDPARD_DATA_SPECIFIER_MESSAGE_MASK & (port_id & UDPARD_SUBJECT_ID_MASK));
```

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.h
> +#define UDPARD_MTU_MAX 1400U /// Can update up to 1500.
I can? Why don't I? (make this comment more useful)

2023-04-27 21:30 UTC, thirtytwobits commented on libudpard/udpard.h
> +#define UDPARD_MTU_UDP_IPV4 UDPARD_MTU_MAX // Minimum MTU for IPv4 for the internet is 576
A good practice is to cite the controlling specification when making assertions like this.

2023-04-27 21:53 UTC, pavel-kirienko commented on libudpard/udpard.c
> -        if (local_node_id <= UDPARD_NODE_ID_MAX)
Presumably because UDPARD_NODE_ID_MAX == UINT16_MAX which makes the check redundant.

2023-04-27 21:56 UTC, pavel-kirienko commented on libudpard/udpard.c
> -        if (local_node_id <= UDPARD_NODE_ID_MAX)
However, NODE_ID_MAX is defined incorrectly, as it should be one less than the maximum, so the check needs to be restored

2023-05-11 16:22 UTC, SchoberMJ commented on libudpard/udpard.c
> +    if (frame->source_node_id != UDPARD_NODE_ID_UNSET)
UDPARD_NODE_ID_UNSET == UDPARD_NODE_ID_MAX so the check is redundant.

2023-05-11 16:24 UTC, pavel-kirienko commented on libudpard/udpard.c
> +    if (frame->source_node_id != UDPARD_NODE_ID_UNSET)
`UDPARD_NODE_ID_MAX` should be 65534, because 65535 is not a valid node-ID

2023-05-11 16:51 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +#define UDPARD_MTU_MAX 1400U /// Can update up to 1500.
Does this max account for the additional bytes that will be added for the IP Header and UDP header? Would we cause IP Fragmentation if we set the UDPARD_MTU_MAX to 1500?

2023-05-11 17:30 UTC, pavel-kirienko commented on libudpard/udpard.h
> +#define UDPARD_MTU_MAX 1400U /// Can update up to 1500.
This is technically correct, but there's a catch: the transfer is appended with its CRC upon transmission, which takes 4 bytes. One might expect that a transfer that contains [MTU-3,MTU] bytes of data would be a single-frame transfer, but the library would have to split the CRC into a follow-up frame. I think this should be explained in the comment that if one needs to ensure single-frame transmission, the MTU should be the maximum payload size plus four bytes.

2023-05-11 17:36 UTC, SchoberMJ commented on libudpard/udpard.c
> -        if (local_node_id <= UDPARD_NODE_ID_MAX)
I think this check is still redundant after fix UDPARD_NODE_ID_MAX to be equal to UINT16_MAX -1 since this check will then need to be 
(local_node_id <= UPDARD_NODE_ID_MAX) || (local_node_id == UDPARD_NODE_ID_UNSET == UINT16_MAX)

2023-05-11 18:06 UTC, pavel-kirienko commented on libudpard/udpard.h
> +#define UDPARD_MTU_MAX 1400U /// Can update up to 1500.
ye

2023-05-11 21:46 UTC, thirtytwobits approved these changes

2023-05-11 21:48 UTC, merged