Restart RX Session if out-of-order multiframe transfer received
OpenCyphal-Garage/libudpard pull request #20
Opened 2023-06-06 02:50 UTC by lydia-at-amazon

During on-target testing, it was found that if a frame is received out of order during a multiframe transfer, then libudpard cannot receive any subsequent transfers for any port IDs because it reports an out of memory error. This is because the memory allocated for the out-of-order multiframe transfer is never freed. Since out-of-order multiframe transfers are not currently supported, the best course of action is drop the entire payload and require the user to resend it.

2023-06-06 17:16 UTC, emrainey commented on tests/test_public_roundtrip.cpp
> -                REQUIRE(((-UDPARD_ERROR_OUT_OF_ORDER == ins_rx.rxAccept(ti->tx_deadline_usec,
Was this covering the case where the second frame was received as duplicate with the same index?

2023-06-06 18:00 UTC, thirtytwobits requested changes
When fixing a bug we ask that you provide a test that initially reproduces the bug so that you can demonstrate that your fix has the intended effect.

2023-06-06 18:12 UTC, thirtytwobits approved these changes

2023-06-06 22:40 UTC, lydia-at-amazon commented on tests/test_public_roundtrip.cpp
> -                REQUIRE(((-UDPARD_ERROR_OUT_OF_ORDER == ins_rx.rxAccept(ti->tx_deadline_usec,
Just to confirm before I make the change, each unique transport index should have its own RX session, correct? So, in `rxAcceptFrame`, we should return immediately if `rxs->redundant_transport_index != redundant_transport_index`: https://github.com/OpenCyphal-Garage/libudpard/blob/main/libudpard/udpard.c#L936

2023-06-06 23:27 UTC, lydia-at-amazon commented on tests/test_public_roundtrip.cpp
> -                REQUIRE(((-UDPARD_ERROR_OUT_OF_ORDER == ins_rx.rxAccept(ti->tx_deadline_usec,
I'll make this change in another CR since we're anxious to get the original fix merged. I have already made the change locally so it will be a quick turnaround.

2023-06-06 23:31 UTC, merged

2023-06-07 00:08 UTC, lydia-at-amazon commented on tests/test_public_roundtrip.cpp
> -                REQUIRE(((-UDPARD_ERROR_OUT_OF_ORDER == ins_rx.rxAccept(ti->tx_deadline_usec,
New issue to fix this bug: https://github.com/OpenCyphal-Garage/libudpard/issues/22

2023-06-07 00:19 UTC, lydia-at-amazon commented on tests/test_public_roundtrip.cpp
> -                REQUIRE(((-UDPARD_ERROR_OUT_OF_ORDER == ins_rx.rxAccept(ti->tx_deadline_usec,
PR to fix this bug: https://github.com/OpenCyphal-Garage/libudpard/pull/23