API refinement: make RX pipeline zero-copy as a side effect of the OOO reassembly support
OpenCyphal-Garage/libudpard pull request #38
Opened 2023-07-13 17:05 UTC by pavel-kirienko

Close https://github.com/OpenCyphal-Garage/libudpard/issues/36

Update the RX pipeline as described in https://forum.opencyphal.org/t/refined-requirements-for-the-rx-pipeline-in-libudpard/1938.

Pros:

- Zero-copy RX pipeline

Cons:

- The `udpardRx*Receive` functions take ownership of the payload buffer.
- The memory usage pattern depends on the MTU of the transmitting node even for the same extent. Small MTU --> more payload fragments --> more memory fragments to keep, and vice versa.

The docs are a bit rough around the edges but the idea should be clear. One missing feature is a trivial helper function that takes payload fragments and returns a contiguous chunk of memory instead (this is expensive both memory-wise and time-wise).

2023-07-17 20:44 UTC, thirtytwobits requested changes

2023-07-17 20:44 UTC, thirtytwobits commented on libudpard/udpard.c
> +static inline bool rxParseFrame(const struct UdpardConstPayload datagram_payload, RxFrame* const out)
It'd be super-neat to have more than just pass/fail returned. Getting access to specific failures like "unknown version" or "invalid priority" would help integrators diagnose problems a lot faster.

2023-07-17 20:44 UTC, thirtytwobits commented on libudpard/udpard.c
> +    const uint_fast8_t version = *ptr++;
unsafe access until you check the datagram_payload.size

2023-07-17 20:44 UTC, thirtytwobits commented on libudpard/udpard.h
>      /// The worst situation from the memory management standpoint is when there is a large number of nodes emitting
so...the worst case means you take a runtime hit but is no worse for memory then any other worst-case scenario detailed above, correct?

2023-07-17 20:44 UTC, thirtytwobits commented on libudpard/udpard.h
> +    /// Each instance is of a very small fixed size, so a trivial zero-fragmentation block allocator is sufficient.
but if you are using malloc under the hood doesn't this mean you'll be thrashing the heap with lots of rapid pointer (de)allocations?

2023-07-17 20:44 UTC, thirtytwobits commented on libudpard/udpard.h
> +    size_t                              payload_size;
is this an object size (i.e. size of the aligned memory allocated) or a value size?

2023-07-17 20:44 UTC, thirtytwobits commented on libudpard/udpard.h
> +    struct UdpardPayloadFragmentHandle* payload;
Let's implement a small-transfer optimization here. By default we'd provide storage for one UdpardPayloadFragmentHandle in the transfer and only allocate additional handles if needed. Extra points if we can make this configurable so the user can provide storage for N handles before allocations were needed.

2023-07-17 20:44 UTC, thirtytwobits commented on tests/src/test_intrusive_rx.c
> +    }
why not just make these separate test functions?

2023-07-17 21:30 UTC, pavel-kirienko commented on libudpard/udpard.c
> +/// The primitive deserialization functions are endian-agnostic.
They are endian-agnostic for all spec-compliant encodings. To be spec-compliant, it has to be little-endian; otherwise no warranty. The statement concerns only the target platform executing the code.

2023-07-17 21:30 UTC, pavel-kirienko commented on libudpard/udpard.c
> +/// The primitive deserialization functions are endian-agnostic.
They are endian-agnostic for all spec-compliant encodings. To be spec-compliant, it has to be little-endian; otherwise no warranty. The statement concerns only the target platform executing the code.

2023-07-17 21:33 UTC, pavel-kirienko commented on libudpard/udpard.c
> +static inline bool rxParseFrame(const struct UdpardConstPayload datagram_payload, RxFrame* const out)
Do you want this exposed as `UDPARD_ERROR_`? I don't think it's a great idea because it mixes up failure states of the application itself (like running out of memory or getting a bad parameter) with those of external agents we have no control over (someone can't compile a frame correctly while we're doing good). This means that we will want another diagnostic code and another error hierarchy, perhaps an out-argument writing the diagnostic information via a pointer. Sounds like a plan?

2023-07-17 21:46 UTC, thirtytwobits commented on libudpard/udpard.c
> +static inline bool rxParseFrame(const struct UdpardConstPayload datagram_payload, RxFrame* const out)
Why don't we just return a fast16 type (since, I think this is the size of AVR registers anyway...need to check on this) for errors and reserve 7-bits for diagnostics that we encourage people to ignore. We can then provide documentation for how to interpret these bits when deeper debugging is needed. 

I don't know. Perhaps I'm overcomplicating things but there's just a lot of great error information that gets lost in this code I want to capture somehow. Perhaps just an errno scheme where we never require the user to use the static error data (i.e. we always provide a return value UDPARD_ERROR_ when needed) but we can stuff our data into that field if anybody cares?

2023-07-17 21:47 UTC, pavel-kirienko commented on libudpard/udpard.h
> +    /// Each instance is of a very small fixed size, so a trivial zero-fragmentation block allocator is sufficient.
Exactly. This is why one probably shouldn't be using variable-complexity memory managers with libudpard in real-time applications. Since libudpard, in this revised design, makes many fixed-size allocations (session objects, payload fragment headers, and (if you round up to MTU) TX queue items), so in certain cases one might want to use fixed-size block pool allocators for these. In fact, if you allocate RX frames in MTU-sized chunks (that is, padded up to the MTU size), you don't need heap at all, but only three fixed-size block pool allocators:

- an MTU+overhead block pool for TX queue items and RX frames
- a session-sized pool for session states
- a small payload fragment header-sized pool for, well, payload fragment headers

See? The advantage of this zero-copy design is that it removes variable-size allocations from the library completely (fine print: as long as you are okay with the inner fragmentation incurred by padding your RX/TX frames up to the MTU size). If you want to linearize your received transfer payloads such that they are nicely stored in a contiguous buffer (and you do want that because our Nunavut doesn't support scatter/gather buffers yet, but it's not hard to add), you can allocate one statically. It's far easier to do outside of libudpard because you can guarantee sequential buffer utilization, while libudpard has to cope with the stochastic nature of network traffic, where you don't know which part of which transfer will arrive next.

2023-07-17 21:56 UTC, pavel-kirienko commented on libudpard/udpard.h
> +    size_t                              payload_size;
Do you want this clarified in the doc comment, or do you prefer the field to be renamed?

2023-07-17 22:26 UTC, thirtytwobits commented on libudpard/udpard.h
> +    size_t                              payload_size;
docs is fine.

2023-07-17 22:28 UTC, thirtytwobits commented on libudpard/udpard.c
> +static inline bool rxParseFrame(const struct UdpardConstPayload datagram_payload, RxFrame* const out)
Will move to an issue.

2023-07-17 22:36 UTC, thirtytwobits commented on libudpard/udpard.c
> +static inline bool rxParseFrame(const struct UdpardConstPayload datagram_payload, RxFrame* const out)
https://github.com/OpenCyphal-Garage/libudpard/issues/39

2023-07-17 22:38 UTC, thirtytwobits commented on libudpard/udpard.h
>      /// The worst situation from the memory management standpoint is when there is a large number of nodes emitting
Okay. The term "memory management" suggests the runtime cost of managing memory rather than the amount of memory required. How about "The worst-case memory consumption is when..."

2023-07-17 22:38 UTC, thirtytwobits commented on libudpard/udpard.h
> +    /// Each instance is of a very small fixed size, so a trivial zero-fragmentation block allocator is sufficient.
Okay.

2023-07-18 20:48 UTC, lydia-at-amazon commented
> Cons:
> 
>     The udpardRx*Receive functions take ownership of the payload buffer.

Just want to document what we talked about in the dev call, the zero-copy design assumes that udpard can directly take over ownership of the buffer from the network stack. A lot of microcontrollers use DMA to store the payload buffer in a section of memory that udpard would not be able to take ownership of and would require making a copy. Are we going to provide an API to allow for this case?

2023-07-18 20:48 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    struct UdpardPayloadFragmentHandle* payload;
A related topic we talked about in the dev call is defining the max number of fragments for a transfer that the library can handle instead of needing to dynamically allocate memory. The default max could be overridden by the user as a compile-time argument. This might also make reassembling out of order transfers easier because you could calculate the offset that each frame should start at, though the zero-copy design already solves this problem.

2023-07-18 20:49 UTC, lydia-at-amazon commented on libudpard/udpard.h
>      /// The worst situation from the memory management standpoint is when there is a large number of nodes emitting
>  if the transfers are never finished, the fragments will reside in memory.
Should we have a timeout for how long a transfer can take to finish? And, if we exceed that limit, then we free the memory for the fragments.

2023-07-18 20:50 UTC, lydia-at-amazon commented
> One missing feature is a trivial helper function that takes payload fragments and returns a contiguous chunk of memory instead (this is expensive both memory-wise and time-wise).

Do we have a ticket for this? I think almost all applications are going to want the contiguous chunk of memory and not the fragments, so we're kind of feature incomplete without this function.

2023-07-18 21:57 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +void udpardRxRPCDispatcherDestroy(struct UdpardRxRPCDispatcher* const self);
Why rename `Service` to `RPC`? I'm confused by the specification:

Section 2.1.1.1 
Service invocation — The communication method for one-to-one request/response interactions (9)
(9) Like remote procedure call (RPC)

Is Service Invocation "like" RPC or is it RPC?

2023-07-18 21:57 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    /// when the corresponding UDP datagram is received. If the library chooses to keep the frame payload
Will not work if udpard isn't able to take ownership of the DMA region where the payload is stored by the network stack

2023-07-18 21:57 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    /// begins a multi-frame transfer while never completing it.
Should we have a timeout for how long a transfer can take to complete so that we don't run out of memory?

2023-07-18 21:57 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    /// the application is guaranteed to never encounter an out-of-memory (OOM) error at runtime.
Can't guarantee this if we never free the fragments for a multi-frame transfer that didn't complete

2023-07-18 21:57 UTC, lydia-at-amazon commented on libudpard/udpard.c
> +            const uint_fast8_t prio = *ptr++;
nit: Don't abbreviate, use `priority`

2023-07-18 21:57 UTC, lydia-at-amazon commented on libudpard/udpard.c
> +                uint32_t index_eot   = 0;
Where does `index_eot` get incremented or have we not added that part yet?

2023-07-18 23:00 UTC, pavel-kirienko commented
>Are we going to provide an API to allow for this case?

The plan is to let the application copy the data from the memory managed by the NIC driver into a new buffer and move it into the library. This solution does not require new API. We can optionally provide convenience functions for this later.

2023-07-18 23:03 UTC, pavel-kirienko commented on libudpard/udpard.h
> +void udpardRxRPCDispatcherDestroy(struct UdpardRxRPCDispatcher* const self);
Sorry, I provided the rationale in the commit message but forgot to add it to the thread. The reason is that RPC is shorter to spell while "Service" makes the function names exceed the limit of 31 characters set by MISRA.

2023-07-18 23:04 UTC, pavel-kirienko commented on libudpard/udpard.h
> +void udpardRxRPCDispatcherDestroy(struct UdpardRxRPCDispatcher* const self);
We can go back to "Service" but then we'll need to rename a few functions to stay within the 31 symbol limit.

2023-07-18 23:06 UTC, pavel-kirienko commented on libudpard/udpard.h
> +    /// when the corresponding UDP datagram is received. If the library chooses to keep the frame payload
See my earlier comment. It works if the application copies the payload beforehand into a memory region it controls.

2023-07-18 23:12 UTC, pavel-kirienko commented on libudpard/udpard.h
> +    /// begins a multi-frame transfer while never completing it.
That is possible, but then we will need to traverse all sessions periodically to find timed out transfers. This may be difficult to arrange in some time-sensitive applications.

Alternatively, we could keep a view of all sessions ordered by the last update time, and check that view every time the receive function is invoked, without having to extend the API. The default timeout could be some multiple of the transfer-ID timeout. This can be done after the "significant completion" is reached.

2023-07-18 23:15 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    /// begins a multi-frame transfer while never completing it.
Agreed, sounds good.

2023-07-18 23:17 UTC, pavel-kirienko commented on libudpard/udpard.h
> +    /// the application is guaranteed to never encounter an out-of-memory (OOM) error at runtime.
These don't accumulate indefinitely. There may be at most one incomplete pair of transfers per remote node (I say "pair" because we keep two transfers per session to support interleaving), the size of each is limited by the configured extent value for the port. It may become a problem only if the number of transmitting nodes is unknown.

2023-07-18 23:17 UTC, pavel-kirienko commented on libudpard/udpard.c
> +                uint32_t index_eot   = 0;
udpardTxPublish et al

2023-07-18 23:21 UTC, lydia-at-amazon commented on libudpard/udpard.c
> +                uint32_t index_eot   = 0;
Oh right, that was in the last CR, sorry.

2023-07-19 18:42 UTC, thirtytwobits commented on tests/src/test_intrusive_rx.c
> +static void testRxParseFrameValidMessage(void)
SO much better!

2023-07-19 18:45 UTC, thirtytwobits commented on libudpard/udpard.h
> +/// Typically, if block pool allocators are used, the following block sizes should be served:
❤️

2023-07-21 17:47 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    /// when the corresponding UDP datagram is received. If the library chooses to keep the frame payload
> The plan is to let the application copy the data from the memory managed by the NIC driver into a new buffer and move it into the library. This solution does not require new API. We can optionally provide convenience functions for this later.

I like the idea of providing convenience functions at some point in the future.

2023-07-21 17:51 UTC, lydia-at-amazon commented on libudpard/udpard.h
>      /// The worst situation from the memory management standpoint is when there is a large number of nodes emitting
Related ticket: #41

2023-07-21 17:53 UTC, lydia-at-amazon commented on libudpard/udpard.h
> +    /// begins a multi-frame transfer while never completing it.
Related ticket: #41

2023-07-22 10:31 UTC, merged