Add RPC service support to the RX pipeline
OpenCyphal-Garage/libudpard pull request #47
Opened 2023-08-11 17:17 UTC by pavel-kirienko

This is the final feature.

This changeset slightly modifies the error handling behavior of `udpardRxSubscriptionReceive` such that the datagram is deallocated if the passed arguments are invalid, unless `self` is also invalid. This is needed to prevent memory leak when the function is invoked incorrectly. An alternative solution is to state it explicitly in the API that the caller is required to free the datagram memory if `-UDPARD_ERROR_ARGUMENT` is returned, but this convention is comparatively fragile. A new test is added for this.

`UdpardRxRPC` is renamed into `UdpardRxRPCPort` for clarity.

`UdpardRxRPCDispatcher` is extended with `local_node_id` to facilitate destination address check when accepting frames.

After this one is accepted, the next steps are:
- The internal e2e test (I am currently working on it).
- A demo application in C that also serves as a high-level integration test. My original plan was to make it interact with a PyCyphal script but I am now considering a slightly different approach where the interaction will be arranged with a simple bash script based on Yakut. Stay tuned.

2023-08-14 19:00 UTC, thirtytwobits requested changes
Only the comment about the documented ownership model is blocking here. The rest of the comments are minor.

2023-08-14 19:00 UTC, thirtytwobits commented on libudpard/udpard.h
> +/// In the case of an invalid argument error the library will attempt to free the datagram payload buffer.
But for other errors it won't? The contract here seems incomplete. We either say that the method will always take ownership freeing immediately for any errors or propagating the pointer for success; or we have to be explicit about which error codes the user has to handle where the caller still owns the memory.

2023-08-14 20:31 UTC, pavel-kirienko commented on libudpard/udpard.c
> +        (void) item;
The only possible reason for the `item` to go missing is a logic error in the implementation. A few lines higher we call `udpardRxRPCDispatcherCancel` which ensures that there is no such item in the tree; therefore, the subsequent invocation of `cavlSearch` with a valid factory argument will necessarily add the new item to the tree, which is then returned. Getting NULL implies that the Cavl library is malfunctioning or is invoked incorrectly because it is required to invoke the factory if the sought node is not in the tree and the factory is given.

2023-08-14 20:40 UTC, pavel-kirienko commented on libudpard/udpard.c
> +            }
Added a clarifying comment for this.

Note that this case returns zero, not an error.

2023-08-14 20:41 UTC, pavel-kirienko commented on libudpard/udpard.h
> +/// In the case of an invalid argument error the library will attempt to free the datagram payload buffer.
Rewrote for clarity.

2023-08-18 18:01 UTC, thirtytwobits approved these changes

2023-08-18 18:33 UTC, merged