Add 2e2 tests and restructure the CMake project
OpenCyphal-Garage/libudpard pull request #48
Opened 2023-08-18 18:55 UTC by pavel-kirienko

- Add e2e tests.
- Create a top-level CMakeLists.txt to simplify development.
- Remove a redundant .clang-format file.

This changeset completes the functionality of the library and its test suite. The missing part is the usage overview for the README and the contributing documentation.

2023-08-22 16:49 UTC, thirtytwobits requested changes
The only sticking point is documentation on dynamic priority changes (see comments). It'd be nice to have a redundancy e2e test but if you think we've covered this enough elsewhere and if we cover this in the example then I can let it go.

2023-08-22 16:49 UTC, thirtytwobits commented on libudpard/udpard.h
> +/// It is therefore not recommended to change the priority level dynamically.
Hmm. This is a feature we advertise though; that Cyphal, unlike CAN-proper, allows changing message priority dynamically. Instead of this comment, can we document the correct procedure to change message priority without message loss? Something like stopping the publisher, waiting for the tx queues to flush, and then restarting with the new priority?

2023-08-22 16:49 UTC, thirtytwobits commented on tests/CMakeLists.txt
> +set(library_dir "${CMAKE_CURRENT_SOURCE_DIR}/../libudpard")
Don't you mean `set(library_dir "${CMAKE_SOURCE_DIR}/libudpard")`?

2023-08-22 16:49 UTC, thirtytwobits commented on tests/src/test_e2e.cpp
> +UdpardPayload makePayload(const std::string_view& payload)
do we have to require C++17 to build libudpard? I've just spent months ensuring our C++14 build chain works with cyphal. This is a coming wrench I'm not going to enjoy dealing with once we pull this in.

2023-08-22 16:49 UTC, thirtytwobits commented on tests/src/test_e2e.cpp
> +    const std::string_view Eden =
This was totally not my fault.

2023-08-22 16:49 UTC, thirtytwobits commented on tests/src/test_e2e.cpp
> +    const std::string_view Dark = "'Dark. It's so fucking dark,' the captain murmured, and then shot himself.";
😑

2023-08-22 16:49 UTC, thirtytwobits commented on tests/src/test_e2e.cpp
> +    const std::string_view Dark = "'Dark. It's so fucking dark,' the captain murmured, and then shot himself.";
suggest: "Sometimes the pressure gets you down, And the clouds are dark and grey, Just kick them off and let the sun shine through!"

2023-08-22 16:49 UTC, thirtytwobits commented on tests/src/test_e2e.cpp
> +}
Would it be asking too much to do a version of these tests with redundant senders and receivers?

2023-08-22 18:24 UTC, pavel-kirienko commented on libudpard/udpard.h
> +/// It is therefore not recommended to change the priority level dynamically.
I updated the description. It is hard for the sender to guarantee that no message loss will occur as it requires knowledge of the time it takes for the frames to be delivered (merely waiting for them to leave the queue is not a sufficient precondition).

2023-08-22 18:27 UTC, pavel-kirienko commented on tests/src/test_e2e.cpp
> +UdpardPayload makePayload(const std::string_view& payload)
Libudpard does not require C++ as it is written in C. The test suite requires C++20; it can be updated for compatibility with C++14 if necessary. Is it?

2023-08-22 18:27 UTC, pavel-kirienko commented on tests/src/test_e2e.cpp
> +    const std::string_view Dark = "'Dark. It's so fucking dark,' the captain murmured, and then shot himself.";
There is no such line in the book.

2023-08-22 18:32 UTC, pavel-kirienko commented on tests/src/test_e2e.cpp
> +}
I think in this particular test the utility of redundancy is limited because the test is fairly low-level. The library itself is not concerned with redundancy during transmission:

```c
///                             +---> TX PIPELINE ---> UDP SOCKET ---> REDUNDANT INTERFACE A
///                             |
///     SERIALIZED TRANSFERS ---+---> TX PIPELINE ---> UDP SOCKET ---> REDUNDANT INTERFACE B
///                             |
///                             +---> ...
```

In the reception pipeline, redundancy is tested in depth in `test_intrusive_rx.c`, cases `static void testSession*(void)`. Additionally, the e2e test includes intentionally duplicated frames (search for `duplicate`).

2023-08-22 18:32 UTC, pavel-kirienko commented on tests/src/test_e2e.cpp
> +}
The demo I am working on supports redundant interfaces btw.

2023-08-22 19:09 UTC, thirtytwobits commented on tests/src/test_e2e.cpp
> +UdpardPayload makePayload(const std::string_view& payload)
It is, I'm afraid.

2023-08-25 17:22 UTC, lydia-at-amazon commented on tests/src/test_e2e.cpp
> +UdpardPayload makePayload(const std::string_view& payload)
Talked with Pavel at the dev call today and we will address this in a separate PR

2023-08-25 17:22 UTC, lydia-at-amazon approved these changes

2023-08-25 17:48 UTC, pavel-kirienko commented on tests/src/test_e2e.cpp
> +UdpardPayload makePayload(const std::string_view& payload)
Moving to https://github.com/OpenCyphal-Garage/libudpard/issues/49

2023-08-25 18:24 UTC, merged